#######################################################################
# Wiki.js - CONFIGURATION                                             #
#######################################################################
# Full explanation + examples in the documentation:
# https://docs.requarks.io/wiki/install

# ---------------------------------------------------------------------
# Port the main server should listen to (80 by default)
# ---------------------------------------------------------------------

port: 80

# ---------------------------------------------------------------------
# Data Directories
# ---------------------------------------------------------------------

paths:
  repo: ./repo
  data: ./data

# ---------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------

db:
  host: localhost
  port: 5432
  user: wikijs
  pass: wikijsrocks
  db: wiki

# ---------------------------------------------------------------------
# Redis
# ---------------------------------------------------------------------

redis:
  host: localhost
  port: 6379
  db: 0
  password: null

